### ISSUE TITLE
too much recursion on Firefox

### ISSUE THREAD

**Issue by brycekahle** [unshiftio/url-parse#4]
I'm getting these failures now too. See https://travis-ci.org/sockjs/sockjs-client/jobs/44256061

**Comment by elierotenberg** [comment]
Hello,

I'm still getting this issue (in sockjs) as of FF 35.0 on Windows.
Upgrading to 0.2.3 unfortunaly didn't fix it.
I was using sockjs in production for handling a large number of connections simultaneous connections but since the release of FF35 I had to switch to engine.io until this is fixed.

Can you reproduce this bug under FF35.0 as well?

Ref: sockjs/sockjs-client#218

**Comment by 3rd-Eden** [comment]
pfff -__________________________________________- not again.

**Comment by mattj65817** [comment]
I get the same error in Firefox 35.0 on Windows. Firefox 34.0 worked fine. Chrome and IE 10 also work fine. sockjs-client 1.0.0-beta.10.

**Comment by 3rd-Eden** [comment]
New solution without big ass regular expression is passing all tests, (including new tests) and has been released as 1.0.0

**Comment by elierotenberg** [comment]
:+1:
